#compile flags we will be using.
CFLAGS=-Wall -g -DNDEBUG
#our program name
PROGRAM=ex25
#the libs we want to use and be compiled too.
LIBS=ex22.o object.o

all: $(PROGRAM)

#ex22_main:$(LIBS)

clean:
	#rm *.o
	rm $(PROGRAM)
